[beckon]
protocol_version = 1

[upstream]
repository = "moergo-sc/zmk"
base_commit = "2f73a230e2fc7b2bd64a9736181e87bf54338131"
ported_pull_request = 36
ported_pull_request_head = "db2ba9fcd3dec4c7afcf171f123585a9f8292595"
